package kepsek.menuSuratMasuk;

import admin.menuKelolaAkun.TampilanKelolaAkun;
import kepsek.menuSuratKeluar.*;
import admin.menuSuratMasuk.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import java.sql.PreparedStatement;
import lib.PdfDiJpanel;

public class LihatSurat extends javax.swing.JPanel {
    private PdfDiJpanel pdf;
    private String[] data;
    private byte[] fileBiner;
    
    public LihatSurat(String[] data, byte[] fileBiner) {
        initComponents();
        this.data = data;
        this.fileBiner = fileBiner;
        this.pdf = new PdfDiJpanel();
        
        setupContent();
        refreshNotif();
        
    }
    
    private void refreshNotif(){
        if(!this.data[5].equals("Sudah Dibaca") && !this.data[5].equals("Terdisposisi")){
            try{
            PreparedStatement statement = lib.Koneksi.Koneksi().prepareStatement("UPDATE surat_masuk SET status_notifikasi = 'Sudah Dibaca' WHERE no_surat = ?");
            statement.setString(1, this.data[0]);
            boolean result = statement.execute();
            
                String totalNotif = kepsek.DashboardUtama.notif.getText();
                int i = Integer.parseInt(totalNotif);
                kepsek.DashboardUtama.notif.setText(Integer.toString(--i));
            
        }catch(Exception ex){
            Logger.getLogger(TampilanKelolaAkun.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }

    private void setupContent() {
        // Create a panel to hold the content
        javax.swing.JPanel contentPanel = new javax.swing.JPanel();
        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setLayout(new java.awt.BorderLayout());

        // Create the label for "Lombah sekolah jatim"
        javax.swing.JLabel contentLabel = new javax.swing.JLabel();
        contentLabel.setFont(new java.awt.Font("Times New Roman", 0, 16));
        contentLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        contentLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        
                
        try {
            contentLabel.setIcon(pdf.addByteFile(this.fileBiner).getIcon());
        } catch (Exception ex) {
            Logger.getLogger(LihatSurat.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // Add the label to the content panel
        contentPanel.add(contentLabel, java.awt.BorderLayout.CENTER);
        
        // Set the content panel as the view for the scroll pane
        imagePdf.setViewportView(contentPanel);
        imagePdf.setBorder(null);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Kembali = new javax.swing.JButton();
        imagePdf = new javax.swing.JScrollPane();
        iconPeriode1 = new javax.swing.JLabel();
        iconPeriode2 = new javax.swing.JLabel();
        iconPeriode3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(158, 158, 158));
        setMinimumSize(new java.awt.Dimension(860, 483));
        setPreferredSize(new java.awt.Dimension(860, 483));

        Kembali.setBackground(new java.awt.Color(214, 203, 203));
        Kembali.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Kembali.setText("Kembali");
        Kembali.setMinimumSize(new java.awt.Dimension(83, 40));
        Kembali.setPreferredSize(new java.awt.Dimension(80, 40));
        Kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KembaliMouseClicked(evt);
            }
        });
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });

        iconPeriode1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/globalIcon/disposisi-surat50px.png"))); // NOI18N
        iconPeriode1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconPeriode1MouseClicked(evt);
            }
        });

        iconPeriode2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/globalIcon/memperbesar-30px.png"))); // NOI18N
        iconPeriode2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconPeriode2MouseClicked(evt);
            }
        });

        iconPeriode3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/globalIcon/memperkecil-30px.png"))); // NOI18N
        iconPeriode3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconPeriode3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconPeriode1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconPeriode3)
                            .addComponent(iconPeriode2))))
                .addGap(90, 90, 90)
                .addComponent(imagePdf, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iconPeriode1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iconPeriode2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iconPeriode3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                        .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imagePdf))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_KembaliActionPerformed

    private void KembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KembaliMouseClicked
        // TODO add your handling code here:
            kepsek.DashboardUtama.SubPanel.removeAll();
            kepsek.DashboardUtama.SubPanel.add(new kepsek.menuSuratMasuk.TampilanSuratMasuk());
            kepsek.DashboardUtama.SubPanel.revalidate();
            kepsek.DashboardUtama.SubPanel.repaint();
    }//GEN-LAST:event_KembaliMouseClicked

    private void iconPeriode1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPeriode1MouseClicked
        // TODO add your handling code here:
            kepsek.DashboardUtama.SubPanel.removeAll();
            kepsek.DashboardUtama.SubPanel.add(new kepsek.menuSuratMasuk.Disposisi(this.data, this.fileBiner));
            kepsek.DashboardUtama.SubPanel.revalidate();
            kepsek.DashboardUtama.SubPanel.repaint();
    }//GEN-LAST:event_iconPeriode1MouseClicked

    private void iconPeriode2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPeriode2MouseClicked
        // TODO add your handling code here:
         try {
            this.pdf.zoomOut();
            setupContent();
        } catch (Exception ex) {
            Logger.getLogger(admin.menuSuratMasuk.LihatSurat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_iconPeriode2MouseClicked

    private void iconPeriode3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPeriode3MouseClicked
                // TODO add your handling code here:
         try {
            this.pdf.zoomIn();
             setupContent();
        } catch (Exception ex) {
            Logger.getLogger(LihatSurat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_iconPeriode3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Kembali;
    private javax.swing.JLabel iconPeriode1;
    private javax.swing.JLabel iconPeriode2;
    private javax.swing.JLabel iconPeriode3;
    private javax.swing.JScrollPane imagePdf;
    // End of variables declaration//GEN-END:variables
}
