/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com;

/**
 *
 * @author lan
 */
public class DashboardKelolaAccount extends javax.swing.JPanel {

    /**
     * Creates new form DashboardKelolaAccount
     */
    public DashboardKelolaAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelDashboardKelolaAccount = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(950, 600));
        setLayout(null);

        LabelDashboardKelolaAccount.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        LabelDashboardKelolaAccount.setText("Dashboard Kelola Account");
        add(LabelDashboardKelolaAccount);
        LabelDashboardKelolaAccount.setBounds(337, 5, 310, 28);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDashboardKelolaAccount;
    // End of variables declaration//GEN-END:variables
}
