/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com;

/**
 *
 * @author lan
 */
public class DashboardArsipKeluar extends javax.swing.JPanel {

    /**
     * Creates new form DashboardArsipKeluar
     */
    public DashboardArsipKeluar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelDashboardArsipKeluar = new javax.swing.JLabel();

        setLayout(null);

        LabelDashboardArsipKeluar.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        LabelDashboardArsipKeluar.setText("Dashboard Arsip Keluar");
        add(LabelDashboardArsipKeluar);
        LabelDashboardArsipKeluar.setBounds(340, 10, 280, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDashboardArsipKeluar;
    // End of variables declaration//GEN-END:variables
}
