/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com;

/**
 *
 * @author lan
 */
public class DashboardHistory extends javax.swing.JPanel {

    /**
     * Creates new form DashboardHistory
     */
    public DashboardHistory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelDashboardHistory = new javax.swing.JLabel();

        setAlignmentX(0.0F);
        setAlignmentY(100.0F);
        setMaximumSize(new java.awt.Dimension(950, 600));
        setMinimumSize(new java.awt.Dimension(950, 600));
        setLayout(null);

        LabelDashboardHistory.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        LabelDashboardHistory.setText("Dashboard History");
        add(LabelDashboardHistory);
        LabelDashboardHistory.setBounds(337, 5, 220, 28);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDashboardHistory;
    // End of variables declaration//GEN-END:variables
}
