package com;
import lib.database.Query;

public class DashboardHistory extends javax.swing.JPanel {

    Query query = new Query();
    public DashboardHistory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelDashboardHistory = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setAlignmentX(0.0F);
        setAlignmentY(100.0F);
        setMaximumSize(new java.awt.Dimension(950, 600));
        setMinimumSize(new java.awt.Dimension(950, 600));
        setLayout(null);

        LabelDashboardHistory.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        LabelDashboardHistory.setText("Dashboard History");
        add(LabelDashboardHistory);
        LabelDashboardHistory.setBounds(337, 5, 220, 28);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(340, 170, 190, 70);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        String[] atributs = {"no_reg","nama","alamat","tgl_daftar","tgl_lahir","jam_daftar"};
//        String[] values = {"74","cupu","rumah","2024-04-21","2003-11-11","09:40:30"};
//        query.setNamaTabel("data_anggota").setAtribut(atributs).setValue(values).setWhereIdUpdate(atributs[0], values[0]).update();

query.setNamaTabel("data_anggota").setWhereId("no_reg", "74").delete();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDashboardHistory;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
