package com;
//Masih Mulai Awal pengembangan
/**
 * -Dashboard Login diutamakan
 */
import java.awt.Color;
import javax.swing.JPanel;

public class ManagementArsipSurat extends javax.swing.JFrame {
    
    DashboardArsipKeluar ArsipKeluar = new DashboardArsipKeluar();
    DashboardArsipMasuk ArsipMasuk = new DashboardArsipMasuk();
    DashboardArsipkanSurat ArsipkanSurat = new DashboardArsipkanSurat();
    DashboardKelolaAccount KelolaAccount = new DashboardKelolaAccount();
    DashboardTrash Trash = new DashboardTrash();
    DashboardHistory History = new DashboardHistory();

    public ManagementArsipSurat() {
        initComponents();
        
        HalamanMenu.setVisible(false);
        PanelWadah.setVisible(false);
        HalamanLogin.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUtama = new javax.swing.JPanel();
        HalamanMenu = new javax.swing.JPanel();
        ButtonSuratMasuk = new javax.swing.JButton();
        ButtonSuratKeluar = new javax.swing.JButton();
        ButtonArsipkanSurat = new javax.swing.JButton();
        ButtonTrash = new javax.swing.JButton();
        ButtonKelolaAccount = new javax.swing.JButton();
        ButtonHistory = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        PanelWadah = new javax.swing.JPanel();
        HalamanLogin = new javax.swing.JPanel();
        LabelDashboardLogin = new javax.swing.JLabel();
        FieldUsername = new javax.swing.JTextField();
        ButtonLogin = new javax.swing.JButton();
        LabelUsername = new javax.swing.JLabel();
        FieldPassword = new javax.swing.JTextField();
        LabelPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Management Arsip Surat");

        PanelUtama.setMinimumSize(new java.awt.Dimension(950, 600));
        PanelUtama.setPreferredSize(new java.awt.Dimension(1226, 617));
        PanelUtama.setLayout(null);

        HalamanMenu.setBackground(new java.awt.Color(255, 255, 255));
        HalamanMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        HalamanMenu.setPreferredSize(new java.awt.Dimension(240, 600));
        HalamanMenu.setLayout(null);

        ButtonSuratMasuk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonSuratMasuk.setText("Surat Masuk");
        ButtonSuratMasuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ButtonSuratMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSuratMasukActionPerformed(evt);
            }
        });
        HalamanMenu.add(ButtonSuratMasuk);
        ButtonSuratMasuk.setBounds(30, 160, 180, 40);

        ButtonSuratKeluar.setText("Surat Keluar");
        ButtonSuratKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSuratKeluarActionPerformed(evt);
            }
        });
        HalamanMenu.add(ButtonSuratKeluar);
        ButtonSuratKeluar.setBounds(30, 220, 180, 40);

        ButtonArsipkanSurat.setText("Arsipkan Surat");
        ButtonArsipkanSurat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonArsipkanSuratActionPerformed(evt);
            }
        });
        HalamanMenu.add(ButtonArsipkanSurat);
        ButtonArsipkanSurat.setBounds(30, 280, 180, 40);

        ButtonTrash.setText("Trash");
        ButtonTrash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTrashActionPerformed(evt);
            }
        });
        HalamanMenu.add(ButtonTrash);
        ButtonTrash.setBounds(30, 400, 180, 40);

        ButtonKelolaAccount.setText("Kelola Account");
        ButtonKelolaAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKelolaAccountActionPerformed(evt);
            }
        });
        HalamanMenu.add(ButtonKelolaAccount);
        ButtonKelolaAccount.setBounds(30, 340, 180, 40);

        ButtonHistory.setText("History");
        ButtonHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHistoryActionPerformed(evt);
            }
        });
        HalamanMenu.add(ButtonHistory);
        ButtonHistory.setBounds(30, 460, 180, 40);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/images.jpeg"))); // NOI18N
        Logo.setText("jLabel1");
        HalamanMenu.add(Logo);
        Logo.setBounds(50, 10, 150, 140);

        PanelUtama.add(HalamanMenu);
        HalamanMenu.setBounds(0, 0, 240, 600);

        PanelWadah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelWadah.setMinimumSize(new java.awt.Dimension(950, 600));
        PanelWadah.setPreferredSize(new java.awt.Dimension(950, 600));
        PanelWadah.setLayout(new java.awt.BorderLayout());
        PanelUtama.add(PanelWadah);
        PanelWadah.setBounds(260, 0, 950, 600);

        HalamanLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        HalamanLogin.setMinimumSize(new java.awt.Dimension(613, 308));
        HalamanLogin.setPreferredSize(new java.awt.Dimension(613, 308));
        HalamanLogin.setLayout(null);

        LabelDashboardLogin.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        LabelDashboardLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDashboardLogin.setText("Dashboard Login");
        HalamanLogin.add(LabelDashboardLogin);
        LabelDashboardLogin.setBounds(0, 10, 610, 32);
        HalamanLogin.add(FieldUsername);
        FieldUsername.setBounds(210, 90, 190, 30);

        ButtonLogin.setText("Login");
        ButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoginActionPerformed(evt);
            }
        });
        HalamanLogin.add(ButtonLogin);
        ButtonLogin.setBounds(230, 230, 150, 40);

        LabelUsername.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelUsername.setText("Username: ");
        HalamanLogin.add(LabelUsername);
        LabelUsername.setBounds(210, 60, 120, 30);
        HalamanLogin.add(FieldPassword);
        FieldPassword.setBounds(210, 160, 190, 30);

        LabelPassword.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelPassword.setText("Password:");
        HalamanLogin.add(LabelPassword);
        LabelPassword.setBounds(210, 130, 120, 30);

        PanelUtama.add(HalamanLogin);
        HalamanLogin.setBounds(308, 154, 613, 308);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSuratKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSuratKeluarActionPerformed
        //LANA
        PanelWadah.removeAll();
        PanelWadah.add(ArsipKeluar);
        PanelWadah.revalidate();
        PanelWadah.repaint();
    }//GEN-LAST:event_ButtonSuratKeluarActionPerformed

    private void ButtonArsipkanSuratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonArsipkanSuratActionPerformed
        //AZIZ DAN THIO
        PanelWadah.removeAll();
        PanelWadah.add(ArsipkanSurat);
        PanelWadah.revalidate();
        PanelWadah.repaint();
    }//GEN-LAST:event_ButtonArsipkanSuratActionPerformed

    private void ButtonTrashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTrashActionPerformed
        //Lana
        PanelWadah.removeAll();
        PanelWadah.add(Trash);
        PanelWadah.revalidate();
        PanelWadah.repaint();
    }//GEN-LAST:event_ButtonTrashActionPerformed

    private void ButtonKelolaAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKelolaAccountActionPerformed
        //GALANG
        PanelWadah.removeAll();
        PanelWadah.add(KelolaAccount);
        PanelWadah.revalidate();
        PanelWadah.repaint();
    }//GEN-LAST:event_ButtonKelolaAccountActionPerformed

    private void ButtonHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHistoryActionPerformed
        //Lana
        PanelWadah.removeAll();
        PanelWadah.add(History);
        PanelWadah.revalidate();
        PanelWadah.repaint();
    }//GEN-LAST:event_ButtonHistoryActionPerformed

    private void ButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoginActionPerformed
        //HASAN
        if(FieldUsername.getText().equals("lana")){
                    HalamanMenu.setVisible(true);
                    PanelWadah.setVisible(true);
                    HalamanLogin.setVisible(false);
        }
    }//GEN-LAST:event_ButtonLoginActionPerformed

    private void ButtonSuratMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSuratMasukActionPerformed
        //Lana
        PanelWadah.removeAll();
        PanelWadah.add(ArsipMasuk);
        PanelWadah.revalidate();
        PanelWadah.repaint();
    }//GEN-LAST:event_ButtonSuratMasukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagementArsipSurat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagementArsipSurat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagementArsipSurat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagementArsipSurat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManagementArsipSurat Frame = new ManagementArsipSurat();
                Frame.setLocationRelativeTo(null);
                Frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonArsipkanSurat;
    private javax.swing.JButton ButtonHistory;
    private javax.swing.JButton ButtonKelolaAccount;
    private javax.swing.JButton ButtonLogin;
    private javax.swing.JButton ButtonSuratKeluar;
    private javax.swing.JButton ButtonSuratMasuk;
    private javax.swing.JButton ButtonTrash;
    private javax.swing.JTextField FieldPassword;
    private javax.swing.JTextField FieldUsername;
    private javax.swing.JPanel HalamanLogin;
    private javax.swing.JPanel HalamanMenu;
    private javax.swing.JLabel LabelDashboardLogin;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JLabel LabelUsername;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JPanel PanelWadah;
    // End of variables declaration//GEN-END:variables
}
