
package waka.notifikasi;

import java.awt.Color;
import java.awt.Graphics;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.border.LineBorder;
import lib.PdfDiJpanel;
import lib.Query;

public class LihatSuratv2 extends javax.swing.JPanel {
    
    private String noDis;
    private String noSurat;
    private String perihall;
    private String tglDisposisi;
    private String catatanDisposisi;
    private String fileBiner;
    private PdfDiJpanel pdf;
    private String role;
    private String statusBaca;
    private String statusDisposisi;
    
    public LihatSuratv2(String noDis, String noSurat, String perihall, String tglDisposisi, String catatanDisposisi, String fileBiner, String role, String statusBaca, String statusDisposisi) {
        initComponents();
        waka.DashboardUtama.Judul.setText("Lihat Surat");
        this.noDis = noDis;
        this.noSurat = noSurat;
        this.perihall = perihall;
        this.tglDisposisi = tglDisposisi;
        this.catatanDisposisi = catatanDisposisi;
        this.fileBiner = fileBiner;
        this.role = role;
        this.statusBaca = statusBaca;
        this.statusDisposisi = statusDisposisi;
        this.pdf = new PdfDiJpanel();
        
        try {
            byte[] pdfBytes = Base64.getDecoder().decode(fileBiner);
            imagePdf.setIcon(this.pdf.addByteFile(pdfBytes).getIcon());
        } catch (Exception ex) {
            Logger.getLogger(LihatSuratv2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
        @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        ImageIcon background = new ImageIcon(getClass().getResource("/bahan/background/backgroundPanel800x483px.png"));
        g.drawImage(background.getImage(), 0, 0, getWidth(), getHeight(), this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLihatsurat = new javax.swing.JScrollPane();
        imagePdf = new javax.swing.JLabel();
        zoomOut = new javax.swing.JLabel();
        iconPeriode4 = new javax.swing.JLabel();
        kembali1 = new java.awt.Panel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(158, 158, 158));
        setMinimumSize(new java.awt.Dimension(860, 483));
        setPreferredSize(new java.awt.Dimension(860, 483));

        panelLihatsurat.setViewportView(imagePdf);

        zoomOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/globalIcon/memperbesar-30px.png"))); // NOI18N
        zoomOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zoomOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                zoomOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                zoomOutMouseExited(evt);
            }
        });

        iconPeriode4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/globalIcon/memperkecil-30px.png"))); // NOI18N
        iconPeriode4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconPeriode4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconPeriode4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconPeriode4MouseExited(evt);
            }
        });

        kembali1.setBackground(new java.awt.Color(255, 255, 255));
        kembali1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembali1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kembali1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kembali1MouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/globalIcon/kembali-30px.png"))); // NOI18N

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel14.setText("Kembali");

        javax.swing.GroupLayout kembali1Layout = new javax.swing.GroupLayout(kembali1);
        kembali1.setLayout(kembali1Layout);
        kembali1Layout.setHorizontalGroup(
            kembali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kembali1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        kembali1Layout.setVerticalGroup(
            kembali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kembali1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zoomOut)
                    .addComponent(iconPeriode4)
                    .addComponent(kembali1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101)
                .addComponent(panelLihatsurat, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(zoomOut, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(iconPeriode4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                        .addComponent(kembali1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelLihatsurat))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void zoomOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zoomOutMouseClicked
        try {
            this.pdf.zoomOut();
            imagePdf.setIcon(this.pdf.getIcon());
        } catch (Exception ex) {
            Logger.getLogger(LihatSuratv2.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_zoomOutMouseClicked

    private void zoomOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zoomOutMouseEntered
        zoomOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); // Ubah kursor saat mouse masuk
        zoomOut.setBorder(new LineBorder(Color.BLACK, 1)); // Add black border
    }//GEN-LAST:event_zoomOutMouseEntered

    private void zoomOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zoomOutMouseExited
        zoomOut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR)); // Kembalikan kursor saat mouse keluar
        zoomOut.setBorder(null);
    }//GEN-LAST:event_zoomOutMouseExited

    private void zoomInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zoomInMouseClicked
        try {
            this.pdf.zoomIn();
            imagePdf.setIcon(this.pdf.getIcon());
        } catch (Exception ex) {
            Logger.getLogger(LihatSuratv2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_zoomInMouseClicked

    private void zoomInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zoomInMouseEntered
        iconPeriode4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); // Ubah kursor saat mouse masuk
    }//GEN-LAST:event_zoomInMouseEntered

    private void zoomInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zoomInMouseExited
        iconPeriode4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR)); // Kembalikan kursor saat mouse keluar
    }//GEN-LAST:event_zoomInMouseExited

    private void kembali1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembali1MouseClicked

              
            waka.DashboardUtama.SubPanel.removeAll();
            waka.DashboardUtama.SubPanel.add(new waka.notifikasi.LembarDisposisi(noDis, noSurat, perihall, tglDisposisi, catatanDisposisi, fileBiner, this.role, this.statusBaca, this.statusDisposisi));
            waka.DashboardUtama.SubPanel.revalidate();
            waka.DashboardUtama.SubPanel.repaint();
    }//GEN-LAST:event_kembali1MouseClicked

    private void kembali1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembali1MouseEntered
        kembali1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); // Ubah kursor saat mouse masuk
        kembali1.setBackground(new java.awt.Color(217, 217, 217));
    }//GEN-LAST:event_kembali1MouseEntered

    private void kembali1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembali1MouseExited
        kembali1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR)); // Kembalikan kursor saat mouse keluar
        kembali1.setBackground(new java.awt.Color(255,255,255)); // Kembalikan warna saat dilepaskan
    }//GEN-LAST:event_kembali1MouseExited

    private void iconPeriode4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPeriode4MouseExited
        iconPeriode4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR)); // Kembalikan kursor saat mouse keluar
        iconPeriode4.setBorder(null);
    }//GEN-LAST:event_iconPeriode4MouseExited

    private void iconPeriode4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPeriode4MouseEntered
        iconPeriode4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); // Ubah kursor saat mouse masuk
        iconPeriode4.setBorder(new LineBorder(Color.BLACK,1));
    }//GEN-LAST:event_iconPeriode4MouseEntered

    private void iconPeriode4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPeriode4MouseClicked
          try {
            this.pdf.zoomIn();
            imagePdf.setIcon(this.pdf.getIcon());
        } catch (Exception ex) {
            Logger.getLogger(LihatSuratv2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_iconPeriode4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconPeriode4;
    private javax.swing.JLabel imagePdf;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private java.awt.Panel kembali1;
    private javax.swing.JScrollPane panelLihatsurat;
    private javax.swing.JLabel zoomOut;
    // End of variables declaration//GEN-END:variables
}
