package admin;

import java.awt.Color;

public class DashboardUtama extends javax.swing.JPanel {


    public DashboardUtama() {
        initComponents();
        PanelMenuSuratMasuk.setBackground(Color.decode("#7D0A0A"));
        LabelSuratMasuk.setForeground(Color.decode("#FFFFFF"));
        
        SubPanel.removeAll();
        SubPanel.add(new admin.menuSuratMasuk.TampilanSuratMasuk());
        SubPanel.revalidate();
        SubPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Judul = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panel_surat_keluar = new javax.swing.JPanel();
        iconPeriode1 = new javax.swing.JLabel();
        surat_keluar = new javax.swing.JLabel();
        PanelMenuSuratMasuk = new javax.swing.JPanel();
        iconPeriode2 = new javax.swing.JLabel();
        LabelSuratMasuk = new javax.swing.JLabel();
        panel_kelola_akun = new javax.swing.JPanel();
        iconPeriode3 = new javax.swing.JLabel();
        kelola_akun = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SubPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(158, 158, 158));
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));

        header.setBackground(new java.awt.Color(125, 10, 10));
        header.setMinimumSize(new java.awt.Dimension(1200, 50));
        header.setPreferredSize(new java.awt.Dimension(1200, 80));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Aplikasi Surat Menyurat");

        Judul.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Judul.setForeground(new java.awt.Color(255, 255, 255));
        Judul.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Judul.setText("Home");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 618, Short.MAX_VALUE)
                .addComponent(Judul)
                .addGap(19, 19, 19))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Judul, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(189, 189, 189));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 500));

        panel_surat_keluar.setBackground(new java.awt.Color(217, 217, 217));
        panel_surat_keluar.setPreferredSize(new java.awt.Dimension(200, 70));
        panel_surat_keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_surat_keluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_surat_keluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_surat_keluarMouseExited(evt);
            }
        });

        iconPeriode1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/menuUtama/surat-keluar70px.png"))); // NOI18N

        surat_keluar.setBackground(new java.awt.Color(217, 217, 217));
        surat_keluar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        surat_keluar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        surat_keluar.setText("Surat Keluar");

        javax.swing.GroupLayout panel_surat_keluarLayout = new javax.swing.GroupLayout(panel_surat_keluar);
        panel_surat_keluar.setLayout(panel_surat_keluarLayout);
        panel_surat_keluarLayout.setHorizontalGroup(
            panel_surat_keluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_surat_keluarLayout.createSequentialGroup()
                .addComponent(iconPeriode1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(surat_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        panel_surat_keluarLayout.setVerticalGroup(
            panel_surat_keluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconPeriode1)
            .addComponent(surat_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PanelMenuSuratMasuk.setBackground(new java.awt.Color(217, 217, 217));
        PanelMenuSuratMasuk.setPreferredSize(new java.awt.Dimension(200, 70));
        PanelMenuSuratMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelMenuSuratMasukMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelMenuSuratMasukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelMenuSuratMasukMouseExited(evt);
            }
        });

        iconPeriode2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/menuUtama/surat-masuk70px.png"))); // NOI18N

        LabelSuratMasuk.setBackground(new java.awt.Color(217, 217, 217));
        LabelSuratMasuk.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        LabelSuratMasuk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSuratMasuk.setText("Surat Masuk");

        javax.swing.GroupLayout PanelMenuSuratMasukLayout = new javax.swing.GroupLayout(PanelMenuSuratMasuk);
        PanelMenuSuratMasuk.setLayout(PanelMenuSuratMasukLayout);
        PanelMenuSuratMasukLayout.setHorizontalGroup(
            PanelMenuSuratMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuSuratMasukLayout.createSequentialGroup()
                .addComponent(iconPeriode2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(LabelSuratMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelMenuSuratMasukLayout.setVerticalGroup(
            PanelMenuSuratMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconPeriode2)
            .addComponent(LabelSuratMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panel_kelola_akun.setBackground(new java.awt.Color(217, 217, 217));
        panel_kelola_akun.setPreferredSize(new java.awt.Dimension(200, 70));
        panel_kelola_akun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_kelola_akunMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_kelola_akunMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_kelola_akunMouseExited(evt);
            }
        });

        iconPeriode3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/menuUtama/kelola-akun70px.png"))); // NOI18N

        kelola_akun.setBackground(new java.awt.Color(217, 217, 217));
        kelola_akun.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        kelola_akun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kelola_akun.setText("Kelola Akun");

        javax.swing.GroupLayout panel_kelola_akunLayout = new javax.swing.GroupLayout(panel_kelola_akun);
        panel_kelola_akun.setLayout(panel_kelola_akunLayout);
        panel_kelola_akunLayout.setHorizontalGroup(
            panel_kelola_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kelola_akunLayout.createSequentialGroup()
                .addComponent(iconPeriode3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kelola_akun)
                .addGap(16, 16, 16))
        );
        panel_kelola_akunLayout.setVerticalGroup(
            panel_kelola_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconPeriode3)
            .addComponent(kelola_akun, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(189, 189, 189));

        logout.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/globalIcon/kembali50px.png"))); // NOI18N
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logout)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logout))
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/background/LogoMenu-200x200px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panel_surat_keluar, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                        .addComponent(panel_kelola_akun, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                        .addComponent(PanelMenuSuratMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelMenuSuratMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_surat_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_kelola_akun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        SubPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(SubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panel_surat_keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_surat_keluarMouseClicked
        //berpindah warna atau pilihan dari manu surat masuk ke menu surat keluar
        PanelMenuSuratMasuk.setBackground(Color.decode("#D9D9D9"));
        LabelSuratMasuk.setForeground(Color.decode("#000000"));
        panel_kelola_akun.setBackground(Color.decode("#D9D9D9"));
        kelola_akun.setForeground(Color.decode("#000000"));
        panel_surat_keluar.setBackground(Color.decode("#7D0A0A"));
        surat_keluar.setForeground(Color.decode("#FFFFFF"));
        Judul.setText("Home");
        
        admin.DashboardUtama.SubPanel.removeAll();
        admin.DashboardUtama.SubPanel.add(new admin.menuSuratKeluar.TampilanSuratKeluar());
        admin.DashboardUtama.SubPanel.revalidate();
        admin.DashboardUtama.SubPanel.repaint();
        
    }//GEN-LAST:event_panel_surat_keluarMouseClicked

    private void PanelMenuSuratMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuSuratMasukMouseClicked
        //berpindah warna atau pilihan ke menu surat masuk
        panel_surat_keluar.setBackground(Color.decode("#D9D9D9"));
        surat_keluar.setForeground(Color.decode("#000000"));
        panel_kelola_akun.setBackground(Color.decode("#D9D9D9"));
        kelola_akun.setForeground(Color.decode("#000000"));
        PanelMenuSuratMasuk.setBackground(Color.decode("#7D0A0A"));
        LabelSuratMasuk.setForeground(Color.decode("#FFFFFF"));
        Judul.setText("Home");
        
        admin.DashboardUtama.SubPanel.removeAll();
        admin.DashboardUtama.SubPanel.add(new admin.menuSuratMasuk.TampilanSuratMasuk());
        admin.DashboardUtama.SubPanel.revalidate();
        admin.DashboardUtama.SubPanel.repaint();
        
    }//GEN-LAST:event_PanelMenuSuratMasukMouseClicked

    private void panel_kelola_akunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_kelola_akunMouseClicked
       //berpindah warna atau pilihan ke menu surat masuk
        panel_surat_keluar.setBackground(Color.decode("#D9D9D9"));
        surat_keluar.setForeground(Color.decode("#000000"));
        PanelMenuSuratMasuk.setBackground(Color.decode("#D9D9D9"));
        LabelSuratMasuk.setForeground(Color.decode("#000000"));
        panel_kelola_akun.setBackground(Color.decode("#7D0A0A"));
        kelola_akun.setForeground(Color.decode("#FFFFFF"));
        Judul.setText("Home");
        
        admin.DashboardUtama.SubPanel.removeAll();
        admin.DashboardUtama.SubPanel.add(new admin.menuKelolaAkun.TampilanKelolaAkun());
        admin.DashboardUtama.SubPanel.revalidate();
        admin.DashboardUtama.SubPanel.repaint();
        
        
    }//GEN-LAST:event_panel_kelola_akunMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
      jPanel2.setBackground(new Color(189,189,189));
        
        login.Main.PanelWadah.removeAll();
        login.Main.PanelWadah.add(new login.Login());
        login.Main.PanelWadah.revalidate();
        login.Main.PanelWadah.repaint();
    }//GEN-LAST:event_logoutMouseClicked

    private void PanelMenuSuratMasukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuSuratMasukMouseEntered
    PanelMenuSuratMasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); // Ubah kursor saat mouse masuk
    PanelMenuSuratMasuk.setBackground(new java.awt.Color(172, 10, 10));
    }//GEN-LAST:event_PanelMenuSuratMasukMouseEntered

    private void PanelMenuSuratMasukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuSuratMasukMouseExited
    PanelMenuSuratMasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR)); // Kembalikan kursor saat mouse keluar
    PanelMenuSuratMasuk.setBackground(new java.awt.Color(217,217,217));
    }//GEN-LAST:event_PanelMenuSuratMasukMouseExited

    private void panel_surat_keluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_surat_keluarMouseEntered
 
    panel_surat_keluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); // Ubah kursor saat mouse masuk
    panel_surat_keluar.setBackground(new java.awt.Color(172, 10, 10));
    }//GEN-LAST:event_panel_surat_keluarMouseEntered

    private void panel_surat_keluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_surat_keluarMouseExited
    panel_surat_keluar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR)); // Kembalikan kursor saat mouse keluar
    panel_surat_keluar.setBackground(new java.awt.Color(217,217,217));
    }//GEN-LAST:event_panel_surat_keluarMouseExited

    private void panel_kelola_akunMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_kelola_akunMouseEntered

    panel_kelola_akun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); // Ubah kursor saat mouse masuk
    panel_kelola_akun.setBackground(new java.awt.Color(172, 10, 10));
    }//GEN-LAST:event_panel_kelola_akunMouseEntered

    private void panel_kelola_akunMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_kelola_akunMouseExited

    panel_kelola_akun.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR)); // Kembalikan kursor saat mouse keluar
    panel_kelola_akun.setBackground(new java.awt.Color(217,217,217));
    }//GEN-LAST:event_panel_kelola_akunMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
                jPanel2.setBackground(new Color(158,158,158));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        jPanel2.setBackground(new Color(189,189,189));
    }//GEN-LAST:event_logoutMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Judul;
    private javax.swing.JLabel LabelSuratMasuk;
    private javax.swing.JPanel PanelMenuSuratMasuk;
    public static javax.swing.JPanel SubPanel;
    private javax.swing.JPanel header;
    private javax.swing.JLabel iconPeriode1;
    private javax.swing.JLabel iconPeriode2;
    private javax.swing.JLabel iconPeriode3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel kelola_akun;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel panel_kelola_akun;
    private javax.swing.JPanel panel_surat_keluar;
    private javax.swing.JLabel surat_keluar;
    // End of variables declaration//GEN-END:variables
}
